### ISSUE TITLE
Luôn hỏi tài khoản đăng nhập là gì

### ISSUE THREAD

**Issue by neittien0110** [phuthien007/Waiting-Queue#55]
## Mô tả
- Người dùng có xu hướng bấm vào nút **Đăng nhập**

## Nguyên nhân
Sau khi quét QRCode, giao diện người dùng luôn hiện chức năng **Đăng nhập** ở vị trí đầu tiên. Nút bấm được tải lên rất sớm, trước khi các card số thứ tự hiện ra.

## Giải pháp đề xuất
 1. Nên tạo ra một dòng thông báo *Đang kiểm tra số thứ tự của bạn, Vui lòng đợi trong giây lát*
 2. Xác định sự kiện website nạp xong thì invisible dòng đó, và mới hiện ra nút bấm **Đăng nhập**
```
window.onload = function() {
   // display:none đối với thông báo Đang kiểm tra...
   // display:block đối với nút bấm Đăng nhập
}
```

**Comment by phuthien007** [comment]
Cái này vì luôn loading dữ liệu từ server nên em không để trạng thái loading ở đây được. vì thế nên em đã tách 2 nút đó ra và đưa thêm hướng dẫn quét mã QR vào để tránh việc người dùng không biết
![image](https://github.com/phuthien007/Waiting-Queue/assets/62065030/729b94b0-c0a4-456c-93aa-df128cc52ba8)

**Comment by neittien0110** [comment]
> Cái này vì luôn loading dữ liệu từ server nên em không để trạng thái loading ở đây được. vì thế nên em đã tách 2 nút đó ra và đưa thêm hướng dẫn quét mã QR vào để tránh việc người dùng không biết ![image](https://user-images.githubusercontent.com/62065030/246286812-729b94b0-c0a4-456c-93aa-df128cc52ba8.png)

Không hẳn. Em sử dụng hàm sự kiện onload (https://www.w3schools.com/jsref/event_onload.asp) là phù hợp, Hàm này sẽ chỉ được gọi 1 lần khi website đó được nạp tải thành công. Sau đó, định kỳ em refresh lại số liệu cục bộ theo kiểu tương tác react-dom thì cũng không làm cho hàm onload bị gọi lần 2 đâu.

**Comment by neittien0110** [comment]
Đúng rồi
