### ISSUE TITLE
Chậm cập nhật lại thời gian phục vụ trên máy tính của người quản trị, 

### ISSUE THREAD

**Issue by neittien0110** [phuthien007/Waiting-Queue#56]
## Mô tả
 - Sau khi người quản trị bấm **Tiếp theo** để phục vụ người khác, website cần nhiều thời gian mới cập nhật lại **Thời gian phục vụ**. Thông thường, thông tin trên máy người tham gia còn được cập nhật trước
 
## Mức độ ưu tiên
- Không quan trọng

**Comment by phuthien007** [comment]
Đã kiểm tra, đã sửa
