### ISSUE TITLE
Thêm dòng hướng dẫn quét mã QR trong giao diện hiển thị mã QRCode

### ISSUE THREAD

**Issue by neittien0110** [phuthien007/Waiting-Queue#58]
## Mô tả
- Người tham gia thắc mắc về nội dung của mã QR
![image](https://github.com/phuthien007/Waiting-Queue/assets/8079397/9281b982-cbdf-4922-b937-eab1c025939c)

## Đề xuất
- Thêm 1 dòng hướng dẫn **Quét mã QR và bấm vào liên kết để nhận SỐ THỨ TỰ xếp hàng**

**Comment by phuthien007** [comment]
Đã kiểm tra, đã thêm
